media:
  - name: media
    input: src/public/media
    output: /public/media
    categories: [image, video]
content:
  - name: videos
    label: Videos
    type: collection
    path: 'src/videos'
    filename: '{fields.title}.json'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Body
        type: text
      - name: media
        label: Media
        type: file
        options:
          media: media

  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.